### ISSUE TITLE
Please state minimal infrastructure conditions to install

### ISSUE THREAD

**Issue by vjcitn** [PMBio/limix#23]
Among other failures with python-2.7 and enthought environment I see things like

stvjc@aura ~/LIMIX $ pip install limix
Downloading/unpacking limix
  Downloading limix-0.7.12.tar.gz (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip_build_stvjc/limix/setup.py) egg_info for package limix
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_stvjc/limix/setup.py", line 104, in <module>
        install_distributions(['Cython'])
      File "/tmp/pip_build_stvjc/limix/setup.py", line 90, in install_distributions
        command = pip.commands.install.InstallCommand()
    AttributeError: 'dict' object has no attribute 'install'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_stvjc/limix/setup.py", line 104, in <module>

    install_distributions(['Cython'])

  File "/tmp/pip_build_stvjc/limix/setup.py", line 90, in install_distributions

    command = pip.commands.install.InstallCommand()

AttributeError: 'dict' object has no attribute 'install'

Let me know if there are more details needed, but if you will just indicate what kind
of linux or macosx infrastructure will permit installation that would be fine.

**Comment by vjcitn** [comment]
The document would be more helpful if it indicated that installation, even by pip, requires various additional python packages to be present.  Once cython, numpy, scipy, pandas, h5py are present, limix can be installed via pip
